### ISSUE TITLE
Juan Perez - CTO UPS

### ISSUE THREAD

**Issue by aflies1** [promazo/content#66]
Video: https://drive.google.com/file/d/116W0GZn5WvdZrW8i_HeJwOy_kyMrMrWO/view?usp=sharing

Research: https://docs.google.com/document/d/1laF2gZOrZNUx_DPTzS1QjdxMYNwa0wLGZj3TN5VG_1A/edit

**Comment by aflies1** [comment]
- [x] Research

- [x] Notes on video

- [x] Article Pitch

- [ ] First Draft

- [ ] Second Draft

- [ ] Final Draft

- [ ] Approved by Editor/ProMazo

- [ ] Sent to Interviewee for Approval
