### ISSUE TITLE
Kristen Walters - Blackrock (Fomer Managing Director) Chief Risk Officer Natixis Investmen managers

### ISSUE THREAD

**Issue by aflies1** [promazo/content#80]
Video: https://drive.google.com/open?id=1jQNcPKDiZ9M7ChT32VK2Fyfz16kBPsDz

**Comment by allie-b2** [comment]
Research, video notes, outline: https://docs.google.com/document/d/1zf9KxG8twJX8eZLjrMkCaHKJAvoW9rN7AIH5C2MZdwo/edit

**Comment by allie-b2** [comment]
First Draft: https://docs.google.com/document/d/116h-jiUzheESOEupa2prhALp4q2mzhyQu9mTHvy6Mk8/edit

**Comment by aflies1** [comment]
- [ ] Research

 

- [ ] Notes on video

 

- [ ] Article Pitch

 

- [ ] First Draft

- [ ]  Second Draft

 

- [ ] Final Draft

 

- [ ] Approved by Editor/ProMazo

 

- [ ] Sent to Interviewee for Approval
